# Generated by Django 3.2.4 on 2021-06-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='tracking',
            field=models.ManyToManyField(blank=True, related_name='tracked_by', to='task_app.RegisteredUser', verbose_name='Tracking'),
        ),
    ]
